# Generated by Django 2.1.7 on 2019-04-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusers',
            name='ActionTakenBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LoginMaster'),
        ),
        migrations.AlterField(
            model_name='externalusers',
            name='ApprovalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='externalusers',
            name='UserType',
            field=models.IntegerField(choices=[(1, 'External Guide'), (2, 'External Mentor')]),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='ExternalUserID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='FacultyUserID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='StudentUserID',
            field=models.IntegerField(null=True),
        ),
    ]
