# Generated by Django 2.1.7 on 2019-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190408_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50, unique=True)),
                ('CreatedBy', models.IntegerField()),
                ('ModifiedBy', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
    ]
