# Generated by Django 2.1.7 on 2019-04-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rolemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymaster',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoleMaster'),
        ),
    ]
