# Generated by Django 2.1.7 on 2019-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190408_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmaster',
            name='ProjHasToBe',
            field=models.IntegerField(choices=[(1, 'Always Internal'), (2, 'Always External'), (3, 'Either')]),
        ),
        migrations.AlterField(
            model_name='processmaster',
            name='ProjRegToBeDoneBy',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Faculty')]),
        ),
        migrations.AlterField(
            model_name='processmaster',
            name='ProjShallBeDoneBy',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Team'), (3, 'Either')]),
        ),
    ]
