# Generated by Django 2.1.7 on 2019-04-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190408_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processmaster',
            old_name='InternalFacultyInvolvementNeeded',
            new_name='InternalFaculty_Involvement_Needed',
        ),
    ]
