# Generated by Django 2.1.7 on 2019-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190408_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processmaster',
            old_name='CreatedBy',
            new_name='Created_By',
        ),
        migrations.RenameField(
            model_name='processmaster',
            old_name='EvaluationRole',
            new_name='Evaluator_Role',
        ),
        migrations.RenameField(
            model_name='processmaster',
            old_name='ModifiedBy',
            new_name='Modified_By',
        ),
        migrations.RenameField(
            model_name='processmaster',
            old_name='ProcessReviewed',
            new_name='Process_Reviewed_By',
        ),
        migrations.RemoveField(
            model_name='processmaster',
            name='ProcessReviewedBy',
        ),
        migrations.AddField(
            model_name='processmaster',
            name='Process_Reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
