# Generated by Django 2.1.7 on 2019-04-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190408_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmaster',
            name='Evaluator_Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoleMaster'),
        ),
    ]
