# Generated by Django 2.1.7 on 2019-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190408_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemaster',
            name='ActivityType',
            field=models.IntegerField(choices=[(1, 'Team'), (2, 'Individual'), (3, 'Either')]),
        ),
    ]
