# Generated by Django 2.1.7 on 2019-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190408_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')]),
        ),
    ]
