# Generated by Django 2.1.7 on 2019-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190408_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='ApprovedBy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='DeactivationReason',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')]),
        ),
    ]
