# Generated by Django 2.1.7 on 2019-04-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190408_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='StageID',
        ),
    ]
