# Generated by Django 2.1.7 on 2019-04-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_projects_stageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='TeamMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
    ]
