# Generated by Django 2.1.7 on 2019-04-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190408_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Mentor',
        ),
        migrations.AlterField(
            model_name='projects',
            name='Dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dean', to='app.FacultyMaster'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ExternalGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExternalUsers'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='HOD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HOD', to='app.FacultyMaster'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='InternalGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InternalGuide', to='app.FacultyMaster'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Principal', to='app.FacultyMaster'),
        ),
    ]
