# Generated by Django 2.1.7 on 2019-04-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190409_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageToFileMapping',
            fields=[
                ('uploadID', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(upload_to='')),
                ('FileName', models.CharField(max_length=200)),
                ('FilePath', models.CharField(max_length=200)),
                ('UploadedBy', models.IntegerField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Projects')),
                ('StageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StageMaster')),
            ],
        ),
    ]
