# Generated by Django 2.1.7 on 2019-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_stagetofilemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetofilemapping',
            name='UploadedBy',
            field=models.CharField(max_length=200),
        ),
    ]
