# Generated by Django 2.1.7 on 2019-04-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190409_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetofilemapping',
            name='FileName',
        ),
    ]
