# Generated by Django 2.1.7 on 2019-04-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_stagetofilemapping_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetofilemapping',
            name='FileName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
