# Generated by Django 2.1.7 on 2019-04-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_stagetofilemapping_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageactivities',
            name='ActivityUpload',
        ),
        migrations.AddField(
            model_name='stagemaster',
            name='ActivityUpload',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stageactivities',
            name='ActivityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StageActivityType', to='app.StageMaster'),
        ),
    ]
