# Generated by Django 2.1.7 on 2019-04-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190410_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageactivities',
            name='Status',
            field=models.IntegerField(choices=[(-1, 'Locked'), (0, 'stage Unlovked'), (2, 'Approved'), (1, 'Submitted')]),
        ),
    ]
