# Generated by Django 2.1.7 on 2019-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190410_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmaster',
            name='DerivedUserFrom',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Internal Faculty'), (3, 'External Faculty')]),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='ExternalUserID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='FacultyUserID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='loginmaster',
            name='StudentUserID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='AddStudentApprovalRights',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ChangeExternalGuideRights',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ChangeInternalGuideRights',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ChangeMentorGuideRights',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='CreatedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ModifiedBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='RemoveStudentApprovalRights',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=2),
        ),
        migrations.AlterField(
            model_name='projects',
            name='TermLead',
            field=models.IntegerField(default=None),
        ),
    ]
