# Generated by Django 2.1.7 on 2019-04-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190411_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='AddStudentApprovalRights',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ChangeExternalGuideRights',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ChangeInternalGuideRights',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ChangeMentorGuideRights',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='RemoveStudentApprovalRights',
        ),
    ]
