# Generated by Django 2.1.7 on 2019-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190412_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetofilemapping',
            name='File',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
